# Site
# repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hao Xu (徐 昊)
# title: 2D & 3D Vision 
email: xuhao@cse.cuhk.edu.hk
website: hxwork.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  hxwork
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: balazssandor
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links (https://fontawesome.com/icons?d=gallery&m=free)
additional_links:
- title: google scholar
  icon: fab fa-google
  url: https://scholar.google.com.hk/citations?user=M7qfdFwAAAAJ&hl=zh-CN&oi=sra
- title: another link
  icon: fas fa-envelope
  url: https://mail.google.com/mail/u/0/?fs=1&tf=cm&source=mailto&to=xuhao@cse.cuhk.edu.hk

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Short Bio
about_profile_image: images/xh.png
about_content: | # this will include new lines to allow paragraphs
  I am currently a Ph.D. student at the CSE Department, the Chinese University of Hong Kong (CUHK), supervised by [Prof. Chi-Wing FU, Philip](https://www.cse.cuhk.edu.hk/~cwfu/).
  I received my Master's degree at the School of Information and Communication Engineering from the University of Electronic Science and Technology of China (UESTC)
  , supervised by [Prof. Guanghui LIU](https://scholar.google.com.hk/citations?user=AjfD95EAAAAJ&hl=zh-CN&oi=ao) and 
  [Prof. Shuaicheng LIU](http://www.liushuaicheng.org/). Before that, I got my Bachelor's degree from Sichuan University (SCU). 
  My research interests include 3D registration, 3D point cloud representation, and 3D hand mesh reconstruction.

  [[CV]](collections/CV/CV.pdf)
  
content:
  - title: Education & Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
                
      - layout: left
        title: Ph.D.
        # link: grubhub.com
        # link_text: grubhub.com
        # sub_title: 
        caption: Aug. 2022 - Present
        description: | # this will include new lines to allow paragraphs
            ## **The Chinese University of Hong Kong (CUHK)**
            Computer Science <br />
                
      - layout: left
        title: M.Sc.
        # link: grubhub.com
        # link_text: grubhub.com
        # sub_title: 
        caption: Sept. 2019 - June 2022
        description: | # this will include new lines to allow paragraphs
            ## **University of Electronic Science and Technology of China (UESTC)**
            Information and Communication Engineering <br />

      - layout: left
        title: B.E.
        # link: bmwgroup.com
        # link_text: bmwgroup.com
        # sub_title:  
        caption: Sept. 2015 - June 2019
        description: | # this will include new lines to allow paragraphs
            
            ## **Sichuan University (SCU)**
            Electronic Information Engineering <br />           
            
      # - layout: left
      #   title: Internship
      #   # link: www.msg.group
      #   # link_text: msg.group
      #   # sub_title: 
      #   caption: Dec. 2018 - June 2022
      #   description: | # this will include new lines to allow paragraphs
      #     ## **Megvii Research**
      #     Research Intern <br />
            
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2023
        # caption: 
        # sub_title: <green_mark>Accepted</green_mark>
        description: | # this will include new lines to allow paragraphs
          ## **H2ONet: Hand-Occlusion-and-Orientation-aware Network for Real-time 3D Hand Mesh Reconstruction**

          **Hao Xu**, Tianyu Wang, Xiao Tang, Chi-Wing Fu 

          IEEE/CVF Computer Vision and Pattern Recognition Conference (**CVPR**), 2023.

          [[PDF](https://github.com/hxwork/H2ONet_Pytorch/blob/main/files/final_version.pdf)]
          [Code: [Pytorch](https://github.com/hxwork/H2ONet_Pytorch)]
          [Video: Coming soon]
          [[BibTex](collections/H2ONet/H2ONet.md)]

      - layout: left
        title: 2022
        # caption: 
        # sub_title: <green_mark>Accepted</green_mark>
        description: | # this will include new lines to allow paragraphs
          ## **FINet: Dual Branches Feature Interaction for Partial-to-Partial Point Cloud Registration**

          **Hao Xu**, Nianjin Ye, Shuaicheng Liu, Guanghui Liu, Bing Zeng 

          Thirty-Sixth AAAI Conference on Artificial Intelligence (**AAAI**), 2022.

          [[PDF](https://arxiv.org/pdf/2106.03479.pdf)]
          [Code: [Pytorch](https://github.com/hxwork/FINet_Pytorch), [MegEngine](https://github.com/MegEngine/FINet)]
          [Video: [Youtube](https://www.youtube.com/watch?v=XDmE9iSx9WM), [Bilibili](https://www.bilibili.com/video/BV1z44y1s7up/)]
          [[BibTex](collections/FINet/FINet.md)]

      - layout: left
        title: 2021
        # caption: 
        # sub_title: <green_mark>Accepted</green_mark>
        description: | # this will include new lines to allow paragraphs
          ## **OMNet: Learning Overlapping Mask for Partial-to-Partial Point Cloud Registration**
          
          **Hao Xu**, Shuaicheng Liu, Guangfu Wang, Guanghui Liu, Bing Zeng 

          IEEE/CVF International Conference on Computer Vision (**ICCV**), 2021.

          [[PDF](https://openaccess.thecvf.com/content/ICCV2021/papers/Xu_OMNet_Learning_Overlapping_Mask_for_Partial-to-Partial_Point_Cloud_Registration_ICCV_2021_paper.pdf)]
          [Code: [Pytorch](https://github.com/hxwork/OMNet_Pytorch), [MegEngine](https://github.com/MegEngine/OMNet)]
          [Video: [Youtube](https://www.youtube.com/watch?v=u2lTKsom8oU), [Bilibili](https://www.bilibili.com/video/BV1Ef4y1J7XP/)]
          [[BibTex](collections/OMNet/OMNet.md)]

  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Driver Monitor System
  #       caption: Dec. 2018 - July 2019
  #       # sub_title: Major member
  #       description: | # this will include new lines to allow paragraphs
  #         Design a light-weighted end-to-end network running on an onboard chip to detect smoking, phoning, 
  #         and drinking in driving.
  #       video_path: collections/DMS/DMS_smoke_demo1.mp4
  #       video_path1: collections/DMS/DMS_smoke_demo2.mp4
  #       video_path2: collections/DMS/DMS_phone_demo.mp4

  #     - layout: left
  #       title: NIO Gaze Estimation 
  #       caption: July 2019 - Mar. 2020
  #       # sub_title: Major member
  #       description: | # this will include new lines to allow paragraphs
  #         Design a light-weighted end-to-end network running on an onboard chip to estimate gaze and detect eye closure 
  #         and occlusion at the same time.
  #       video_path: collections/Gaze/gaze_demo.mp4

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-relative-links

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
